package com.qhn.bhne.footprinting.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qhn.bhne.footprinting.entries.Construction;
import com.qhn.bhne.footprinting.entries.FileContent;
import com.qhn.bhne.footprinting.entries.Project;
import com.qhn.bhne.footprinting.entries.User;

import com.qhn.bhne.footprinting.db.ConstructionDao;
import com.qhn.bhne.footprinting.db.FileContentDao;
import com.qhn.bhne.footprinting.db.ProjectDao;
import com.qhn.bhne.footprinting.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig constructionDaoConfig;
    private final DaoConfig fileContentDaoConfig;
    private final DaoConfig projectDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ConstructionDao constructionDao;
    private final FileContentDao fileContentDao;
    private final ProjectDao projectDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        constructionDaoConfig = daoConfigMap.get(ConstructionDao.class).clone();
        constructionDaoConfig.initIdentityScope(type);

        fileContentDaoConfig = daoConfigMap.get(FileContentDao.class).clone();
        fileContentDaoConfig.initIdentityScope(type);

        projectDaoConfig = daoConfigMap.get(ProjectDao.class).clone();
        projectDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        constructionDao = new ConstructionDao(constructionDaoConfig, this);
        fileContentDao = new FileContentDao(fileContentDaoConfig, this);
        projectDao = new ProjectDao(projectDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Construction.class, constructionDao);
        registerDao(FileContent.class, fileContentDao);
        registerDao(Project.class, projectDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        constructionDaoConfig.clearIdentityScope();
        fileContentDaoConfig.clearIdentityScope();
        projectDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ConstructionDao getConstructionDao() {
        return constructionDao;
    }

    public FileContentDao getFileContentDao() {
        return fileContentDao;
    }

    public ProjectDao getProjectDao() {
        return projectDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
