package com.qhn.bhne.footprinting.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.qhn.bhne.footprinting.mvp.entries.Project;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROJECT".
*/
public class ProjectDao extends AbstractDao<Project, Long> {

    public static final String TABLENAME = "PROJECT";

    /**
     * Properties of entity Project.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property UserName = new Property(2, String.class, "userName", false, "USER_NAME");
        public final static Property ChildId = new Property(3, Long.class, "childId", false, "CHILD_ID");
        public final static Property Category = new Property(4, String.class, "category", false, "CATEGORY");
        public final static Property Definition = new Property(5, int.class, "definition", false, "DEFINITION");
        public final static Property Batch = new Property(6, int.class, "batch", false, "BATCH");
        public final static Property Remark = new Property(7, String.class, "remark", false, "REMARK");
        public final static Property Date = new Property(8, String.class, "date", false, "DATE");
        public final static Property Describe = new Property(9, String.class, "describe", false, "DESCRIBE");
        public final static Property ProjectMax = new Property(10, int.class, "projectMax", false, "PROJECT_MAX");
    }

    private DaoSession daoSession;


    public ProjectDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROJECT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL UNIQUE ," + // 1: name
                "\"USER_NAME\" TEXT NOT NULL ," + // 2: userName
                "\"CHILD_ID\" INTEGER UNIQUE ," + // 3: childId
                "\"CATEGORY\" TEXT," + // 4: category
                "\"DEFINITION\" INTEGER NOT NULL ," + // 5: definition
                "\"BATCH\" INTEGER NOT NULL ," + // 6: batch
                "\"REMARK\" TEXT," + // 7: remark
                "\"DATE\" TEXT," + // 8: date
                "\"DESCRIBE\" TEXT," + // 9: describe
                "\"PROJECT_MAX\" INTEGER NOT NULL );"); // 10: projectMax
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROJECT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Project entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getUserName());
 
        Long childId = entity.getChildId();
        if (childId != null) {
            stmt.bindLong(4, childId);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(5, category);
        }
        stmt.bindLong(6, entity.getDefinition());
        stmt.bindLong(7, entity.getBatch());
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(8, remark);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(9, date);
        }
 
        String describe = entity.getDescribe();
        if (describe != null) {
            stmt.bindString(10, describe);
        }
        stmt.bindLong(11, entity.getProjectMax());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Project entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getUserName());
 
        Long childId = entity.getChildId();
        if (childId != null) {
            stmt.bindLong(4, childId);
        }
 
        String category = entity.getCategory();
        if (category != null) {
            stmt.bindString(5, category);
        }
        stmt.bindLong(6, entity.getDefinition());
        stmt.bindLong(7, entity.getBatch());
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(8, remark);
        }
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(9, date);
        }
 
        String describe = entity.getDescribe();
        if (describe != null) {
            stmt.bindString(10, describe);
        }
        stmt.bindLong(11, entity.getProjectMax());
    }

    @Override
    protected final void attachEntity(Project entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Project readEntity(Cursor cursor, int offset) {
        Project entity = new Project( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // userName
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // childId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // category
            cursor.getInt(offset + 5), // definition
            cursor.getInt(offset + 6), // batch
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // remark
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // date
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // describe
            cursor.getInt(offset + 10) // projectMax
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Project entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setUserName(cursor.getString(offset + 2));
        entity.setChildId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setCategory(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDefinition(cursor.getInt(offset + 5));
        entity.setBatch(cursor.getInt(offset + 6));
        entity.setRemark(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setDate(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDescribe(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setProjectMax(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Project entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Project entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Project entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
